import { useState, useEffect, useRef } from "react";
import { API } from "../services/api"; // Make sure we use your clean api.js file!

export default function StudyReels() {
  const [topic, setTopic] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeJobId, setActiveJobId] = useState(null);
  const [jobStatus, setJobStatus] = useState("");
  const [error, setError] = useState("");
  
  // Array of reels for the TikTok-style feed
  const [reels, setReels] = useState([]);
  const videoRefs = useRef([]);

  // --- TIKTOK STYLE SCROLL OBSERVER ---
  useEffect(() => {
    const observerOptions = {
      root: null,
      rootMargin: "0px",
      threshold: 0.7, // Video must be 70% visible to play
    };

    const handleIntersection = (entries) => {
      entries.forEach((entry) => {
        const video = entry.target;
        if (entry.isIntersecting) {
          video.play().catch(e => console.log("Autoplay blocked:", e));
        } else {
          video.pause();
          video.currentTime = 0;
        }
      });
    };

    const observer = new IntersectionObserver(handleIntersection, observerOptions);

    videoRefs.current.forEach((video) => {
      if (video) observer.observe(video);
    });

    return () => observer.disconnect();
  }, [reels]);

  // --- 100% FIXED BACKGROUND POLLING LOGIC ---
  useEffect(() => {
    // 1. Only poll if we have an active job
    if (!activeJobId || !isGenerating) return;

    // 2. Prevent state updates if the user navigates away from the page
    let isMounted = true;
    let timerId;

    const checkStatus = async () => {
      try {
        const res = await fetch(API.jobStatus(activeJobId));
        const data = await res.json();

        // If the component unmounted while fetching, ignore the result
        if (!isMounted) return;

        if (data.error) throw new Error(data.error);

        setJobStatus(data.progress || "Processing...");

        if (data.status === 'completed') {
          setIsGenerating(false);
          setActiveJobId(null);
          setJobStatus("");
          
          // Add the newly generated video to the TOP of the feed
          setReels(prev => [
            {
              id: Date.now().toString(),
              title: `AI Lesson: ${data.topic || topic}`,
              description: data.description || "Generated by NEXUS AI",
              videoUrl: data.videoUrl,
              likes: 0,
            },
            ...prev
          ]);
        } else if (data.status === 'failed') {
          setIsGenerating(false);
          setActiveJobId(null);
          setError(data.error || "Failed to generate video.");
        }
      } catch (err) {
        if (isMounted) console.error("Polling error:", err);
      }
    };

    // 3. Safe, recursive polling (prevents runaway requests)
    const poll = async () => {
      await checkStatus();
      // Only schedule the next poll if we are still waiting on a result
      if (isMounted && isGenerating) {
        timerId = setTimeout(poll, 10000); // Wait 10 full seconds
      }
    };

    // Start the first poll
    poll();

    // 4. Cleanup function 
    return () => {
      isMounted = false;
      if (timerId) clearTimeout(timerId);
    };
  }, [activeJobId, isGenerating]); // Safely scoped dependencies

  // --- GENERATE VIDEO (Start Job) ---
  const generateVideo = async (e) => {
    if (e) e.preventDefault();
    if (!topic.trim()) {
      setError("Enter a topic first");
      return;
    }

    setIsGenerating(true);
    setError("");
    setJobStatus("Connecting to server...");

    try {
      const res = await fetch(API.generateVideo, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic }),
      });

      const data = await res.json();

      if (res.ok && data.jobId) {
        // Save Job ID and clear input. Polling useEffect safely takes over.
        setActiveJobId(data.jobId);
        setTopic(""); 
      } else {
        throw new Error(data.error || "Failed to start generation.");
      }
    } catch (err) {
      console.error(err);
      setError(err.message || "Server connection failed.");
      setIsGenerating(false);
      setJobStatus("");
    }
  };

  // --- LOAD NEXT VIDEO ---
  const loadNext = async () => {
    try {
      const res = await fetch(API.reels);
      const data = await res.json();

      if (data.reels && data.reels.length > 0) {
        // Add fetched reels to the BOTTOM of our feed array
        const formattedReels = data.reels.map(r => ({
          id: crypto.randomUUID(),
          title: r.title || "Study Reel",
          description: "Discover more topics",
          videoUrl: r.videoUrl,
          likes: Math.floor(Math.random() * 100)
        }));
        setReels(prev => [...prev, ...formattedReels]);
      } else {
        setError("Next video still processing on the server...");
      }
    } catch (err) {
      console.error(err);
      setError("Unable to load next reel");
    }
  };

  return (
    <div className="min-h-screen pt-20 pb-10 px-4 md:px-8 max-w-5xl mx-auto flex flex-col md:flex-row gap-8">
      
      {/* --- LEFT COLUMN: GENERATOR SETTINGS --- */}
      <div className="w-full md:w-1/3 space-y-6">
        <div className="card sticky top-24">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center shadow-inner">
              <span className="text-xl drop-shadow-md">🎬</span>
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">AI Study Reels</h2>
              <p className="text-xs text-indigo-300">Powered by NEXUS AI</p>
            </div>
          </div>

          <form onSubmit={generateVideo} className="space-y-4">
            <div>
              <textarea 
                className="input min-h-[100px] resize-none focus:ring-2 focus:ring-indigo-500/50" 
                placeholder="Enter topic (Example: Quantum Physics)"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                required
                disabled={isGenerating}
              />
            </div>

            <button 
              type="submit" 
              className={`btn flex items-center justify-center gap-2 transition-all duration-300 ${
                isGenerating ? 'opacity-50 cursor-not-allowed filter grayscale-[30%]' : 'hover:shadow-[0_0_20px_rgba(99,102,241,0.4)]'
              }`}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>
                  <span className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></span>
                  Processing...
                </>
              ) : (
                "Generate Reel"
              )}
            </button>
          </form>

          {/* DYNAMIC PROGRESS TRACKER */}
          {isGenerating && (
            <div className="mt-6 p-5 rounded-xl bg-slate-900 border border-indigo-500/30 shadow-[0_0_15px_rgba(99,102,241,0.1)] animate-fade-in">
              <div className="flex items-center justify-between mb-3">
                <span className="text-sm font-semibold text-indigo-400">Status: {jobStatus}</span>
                <span className="relative flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-indigo-500"></span>
                </span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
                <div className="bg-gradient-to-r from-indigo-500 to-purple-500 h-2 rounded-full w-full animate-pulse"></div>
              </div>
              <p className="text-[11px] text-slate-400 mt-4 leading-relaxed">
                This process takes about 6-8 minutes. You can safely watch other reels while you wait!
              </p>
            </div>
          )}

          {/* ERROR BOX */}
          {error && (
            <div className="mt-4 p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-sm text-red-400 animate-fade-in flex items-center gap-2">
              <svg className="w-5 h-5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              {error}
            </div>
          )}
        </div>
      </div>

      {/* --- RIGHT COLUMN: TIKTOK STYLE VIDEO FEED --- */}
      <div className="w-full md:w-2/3 flex flex-col items-center">
        
        {reels.length === 0 && !isGenerating ? (
          <div className="w-full max-w-sm h-[700px] flex flex-col items-center justify-center border-2 border-dashed border-white/10 bg-slate-900/30 rounded-3xl text-slate-400 shadow-xl">
            <span className="text-5xl mb-4 drop-shadow-md">📺</span>
            <p className="font-medium text-slate-300">No reels generated yet.</p>
            <p className="text-sm mt-1 mb-6 text-slate-500">Enter a topic to get started.</p>
            <button 
              onClick={loadNext} 
              className="px-5 py-2.5 rounded-full bg-white/5 border border-white/10 text-white text-sm hover:bg-white/10 transition-colors"
            >
              Load public gallery
            </button>
          </div>
        ) : (
          <div className="w-full max-w-sm h-[700px] overflow-y-scroll snap-y snap-mandatory rounded-3xl border border-white/10 shadow-[0_0_50px_rgba(0,0,0,0.5)] bg-[#020617] hide-scrollbar relative">
            
            {reels.map((reel, index) => (
              <div key={reel.id} className="w-full h-full snap-start relative bg-black group flex items-center justify-center">
                
                {/* Video Element */}
                <video 
                  ref={(el) => (videoRefs.current[index] = el)}
                  src={reel.videoUrl} 
                  className="w-full h-full object-cover"
                  controls
                  playsInline
                />

                {/* Video Overlay Info */}
                <div className="absolute bottom-16 left-4 right-4 pointer-events-none bg-black/50 backdrop-blur-md p-4 rounded-2xl border border-white/10 shadow-lg transition-opacity duration-300">
                  <h3 className="text-lg font-bold text-white drop-shadow-md mb-1">{reel.title}</h3>
                  <p className="text-sm text-slate-300 drop-shadow-md line-clamp-2">{reel.description}</p>
                </div>
              </div>
            ))}

            {/* End of Feed / Load More */}
            {reels.length > 0 && (
              <div className="w-full h-32 snap-start flex items-center justify-center bg-[#020617] border-t border-white/5 pb-8">
                <button 
                  onClick={loadNext} 
                  className="px-6 py-3 rounded-full bg-slate-800 text-white font-medium text-sm hover:bg-slate-700 hover:shadow-lg transition-all flex items-center gap-2"
                >
                  <svg className="w-4 h-4 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                  </svg>
                  Scroll for more
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}