import { useState, useEffect, useRef } from "react";

export default function StudyReels() {
  const [topic, setTopic] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeJobId, setActiveJobId] = useState(null);
  const [jobStatus, setJobStatus] = useState("");
  const [error, setError] = useState("");
  
  // Array of reels instead of a single videoUrl for the TikTok-style feed
  const [reels, setReels] = useState([]);
  
  const videoRefs = useRef([]);
  const API = "https://nexus-api-q4u2.onrender.com";

  // --- TIKTOK STYLE SCROLL OBSERVER ---
  useEffect(() => {
    const observerOptions = {
      root: null,
      rootMargin: "0px",
      threshold: 0.7, // Video must be 70% visible to play
    };

    const handleIntersection = (entries) => {
      entries.forEach((entry) => {
        const video = entry.target;
        if (entry.isIntersecting) {
          video.play().catch(e => console.log("Autoplay blocked:", e));
        } else {
          video.pause();
          video.currentTime = 0;
        }
      });
    };

    const observer = new IntersectionObserver(handleIntersection, observerOptions);

    videoRefs.current.forEach((video) => {
      if (video) observer.observe(video);
    });

    return () => observer.disconnect();
  }, [reels]);

  // --- BACKGROUND POLLING LOGIC ---
  useEffect(() => {
    let intervalId;

    if (activeJobId && isGenerating) {
      // Poll the backend every 10 seconds
      intervalId = setInterval(async () => {
        try {
          const res = await fetch(`${API}/job-status/${activeJobId}`);
          const data = await res.json();

          if (data.error) throw new Error(data.error);

          setJobStatus(data.progress || "Processing...");

          if (data.status === 'completed') {
            setIsGenerating(false);
            setActiveJobId(null);
            setJobStatus("");
            
            // Add the newly generated video to the TOP of the feed
            setReels(prev => [
              {
                id: Date.now().toString(),
                title: `AI Lesson: ${data.topic || topic}`,
                description: data.description || "Generated by NEXUS AI",
                videoUrl: data.videoUrl,
                likes: 0,
              },
              ...prev
            ]);
            
            clearInterval(intervalId);
          } else if (data.status === 'failed') {
            setIsGenerating(false);
            setActiveJobId(null);
            setError(data.error || "Failed to generate video.");
            clearInterval(intervalId);
          }
        } catch (err) {
          console.error("Polling error:", err);
        }
      }, 10000); // 10 seconds
    }

    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  }, [activeJobId, isGenerating, topic]);

  // --- GENERATE VIDEO (Start Job) ---
  const generateVideo = async (e) => {
    if (e) e.preventDefault();
    if (!topic.trim()) {
      setError("Enter a topic first");
      return;
    }

    setIsGenerating(true);
    setError("");
    setJobStatus("Connecting to server...");

    try {
      const res = await fetch(`${API}/generate-video`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic }),
      });

      const data = await res.json();

      if (res.ok && data.jobId) {
        // Save Job ID and clear input. Polling useEffect takes over.
        setActiveJobId(data.jobId);
        setTopic(""); 
      } else {
        throw new Error(data.error || "Failed to start generation.");
      }
    } catch (err) {
      console.error(err);
      setError(err.message || "Server connection failed.");
      setIsGenerating(false);
      setJobStatus("");
    }
  };

  // --- LOAD NEXT VIDEO ---
  const loadNext = async () => {
    try {
      const res = await fetch(`${API}/reels`);
      const data = await res.json();

      if (data.reels && data.reels.length > 0) {
        // Add fetched reels to the BOTTOM of our feed array
        const formattedReels = data.reels.map(r => ({
          id: crypto.randomUUID(),
          title: r.title || "Study Reel",
          description: "Discover more topics",
          videoUrl: r.videoUrl,
          likes: Math.floor(Math.random() * 100)
        }));
        setReels(prev => [...prev, ...formattedReels]);
      } else {
        setError("Next video still processing on the server...");
      }
    } catch (err) {
      console.error(err);
      setError("Unable to load next reel");
    }
  };

  return (
    <div className="min-h-screen pt-20 pb-10 px-4 md:px-8 max-w-5xl mx-auto flex flex-col md:flex-row gap-8">
      
      {/* --- LEFT COLUMN: GENERATOR SETTINGS --- */}
      <div className="w-full md:w-1/3 space-y-6">
        <div className="card sticky top-24">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center">
              <span className="text-xl">🎬</span>
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">AI Study Reels</h2>
              <p className="text-xs text-slate-400">Powered by NEXUS AI</p>
            </div>
          </div>

          <form onSubmit={generateVideo} className="space-y-4">
            <div>
              <textarea 
                className="input min-h-[100px] resize-none" 
                placeholder="Enter topic (Example: Quantum Physics)"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                required
                disabled={isGenerating}
              />
            </div>

            <button 
              type="submit" 
              className={`btn flex items-center justify-center gap-2 ${isGenerating ? 'opacity-50 cursor-not-allowed' : ''}`}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>
                  <span className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></span>
                  Processing...
                </>
              ) : (
                "Generate Reel"
              )}
            </button>
          </form>

          {/* DYNAMIC PROGRESS TRACKER */}
          {isGenerating && (
            <div className="mt-6 p-4 rounded-lg bg-slate-900 border border-indigo-500/30">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-semibold text-indigo-400">Status: {jobStatus}</span>
                <span className="relative flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-indigo-500"></span>
                </span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
                <div className="bg-indigo-500 h-1.5 rounded-full w-full animate-pulse"></div>
              </div>
              <p className="text-[10px] text-slate-500 mt-3">This takes 6-8 minutes. You can safely scroll and watch other videos while waiting.</p>
            </div>
          )}

          {/* ERROR BOX */}
          {error && (
            <div className="mt-4 p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-sm text-red-400 animate-fade-in">
              {error}
            </div>
          )}
        </div>
      </div>

      {/* --- RIGHT COLUMN: TIKTOK STYLE VIDEO FEED --- */}
      <div className="w-full md:w-2/3 flex flex-col items-center">
        
        {reels.length === 0 && !isGenerating ? (
          <div className="w-full max-w-sm h-[700px] flex flex-col items-center justify-center border border-dashed border-white/20 rounded-2xl text-slate-400">
            <span className="text-4xl mb-4">📺</span>
            <p>Your generated reels will appear here.</p>
            <button onClick={loadNext} className="mt-4 text-indigo-400 text-sm hover:underline">
              Load public reels
            </button>
          </div>
        ) : (
          <div className="w-full max-w-sm h-[700px] overflow-y-scroll snap-y snap-mandatory rounded-2xl border border-white/10 shadow-[0_0_50px_rgba(0,0,0,0.5)] bg-black hide-scrollbar relative">
            
            {reels.map((reel, index) => (
              <div key={reel.id} className="w-full h-full snap-start relative bg-black group flex items-center justify-center">
                
                {/* Video Element */}
                <video 
                  ref={(el) => (videoRefs.current[index] = el)}
                  src={reel.videoUrl} 
                  className="w-full h-full object-cover rounded-2xl"
                  controls
                  playsInline
                />

                {/* Video Overlay Info */}
                <div className="absolute bottom-16 left-4 right-4 pointer-events-none bg-black/40 backdrop-blur-sm p-3 rounded-xl border border-white/10">
                  <h3 className="text-lg font-bold text-white drop-shadow-md mb-1">{reel.title}</h3>
                  <p className="text-xs text-slate-200 drop-shadow-md line-clamp-2">{reel.description}</p>
                </div>
              </div>
            ))}

            {/* End of Feed / Load More */}
            {reels.length > 0 && (
              <div className="w-full h-32 snap-start flex items-center justify-center bg-black border-t border-white/10">
                <button onClick={loadNext} className="px-6 py-2 rounded-full bg-slate-800 text-white font-medium hover:bg-slate-700 transition-colors">
                  Load More Reels
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}